version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:10000
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
